# envisionhgdetector/dashboard_utils.py
"""
Dashboard utilities for gesture visualization.
Handles dashboard setup, video copying, and CSS generation.
"""

import os
import shutil

import pandas as pd
from dash import Dash, dcc, html, Input, Output
import plotly.express as px


def setup_dashboard_folders(data_folder: str, assets_folder: str) -> None:
    """
    Set up necessary folders for the dashboard.

    This function prepares the dashboard by:
    1. Creating the assets folder if it doesn't exist
    2. Copying tracked videos to the assets folder for web serving
    3. Validating that required data files exist

    Args:
        data_folder: Path to analysis data folder (containing gesture_visualization.csv)
        assets_folder: Path to Dash assets folder (will store videos and CSS)

    Raises:
        FileNotFoundError: If tracked videos folder or visualization data not found
    """
    # Create assets folder if it doesn't exist
    os.makedirs(assets_folder, exist_ok=True)

    # Adjust path to tracked videos to point to the retracked directory
    retracked_folder = os.path.join(
        os.path.dirname(data_folder), "retracked", "tracked_videos"
    )
    if not os.path.exists(retracked_folder):
        raise FileNotFoundError(
            f"Tracked videos folder not found at {retracked_folder}"
        )

    # Copy videos if they don't exist in assets
    copied_count = 0
    for video in os.listdir(retracked_folder):
        if video.endswith("_tracked.mp4"):
            source = os.path.join(retracked_folder, video)
            dest = os.path.join(assets_folder, video)
            if not os.path.exists(dest):
                print(f"Copying {video} to assets folder...")
                shutil.copy2(source, dest)
                copied_count += 1

    # Verify visualization data exists
    viz_path = os.path.join(data_folder, "gesture_visualization.csv")
    if not os.path.exists(viz_path):
        raise FileNotFoundError(f"Visualization data not found at {viz_path}")

    print(f"Dashboard folders set up successfully:")
    print(f"- Assets folder: {assets_folder}")
    print(f"- Data folder: {data_folder}")
    print(f"- {len(os.listdir(assets_folder))} files in assets")
    if copied_count > 0:
        print(f"- Copied {copied_count} new videos")


def create_dashboard(data_folder: str, assets_folder: str = "./assets") -> Dash:
    """
    Create and return the gesture space visualization dashboard.

    The dashboard provides:
    - Interactive UMAP scatter plot of gesture kinematic space
    - Click-to-play video viewer for individual gestures
    - Dark theme with professional styling

    Args:
        data_folder: Path to folder containing visualization data
        assets_folder: Path to Dash assets folder

    Returns:
        Configured Dash application instance (call .run() to start)
    """
    # Create assets folder if it doesn't exist
    os.makedirs(assets_folder, exist_ok=True)

    # Import visualization data
    df = pd.read_csv(os.path.join(data_folder, "gesture_visualization.csv"))

    # Copy tracked videos to assets from the retracked folder
    retracked_folder = os.path.join(
        os.path.dirname(data_folder), "retracked", "tracked_videos"
    )
    if os.path.exists(retracked_folder):
        for video in os.listdir(retracked_folder):
            if video.endswith("_tracked.mp4"):
                source = os.path.join(retracked_folder, video)
                dest = os.path.join(assets_folder, video)
                if not os.path.exists(dest):
                    shutil.copy2(source, dest)

    app = Dash(__name__)

    # App layout
    app.layout = html.Div([
        html.H1(
            "Gesture Kinematic Space Visualization",
            style={'text-align': 'center'}
        ),

        html.H3(
            "This dashboard shows a gesture kinematic space generated by computing "
            "dynamic time warping distances between gesture kinematic 3D timeseries. "
            "Gestures that are closer together in the space are more kinematically similar.",
            style={'text-align': 'center'}
        ),

        html.Div([
            html.Div([
                dcc.Graph(
                    id='gesture-space',
                    figure={},
                    style={'height': '80vh'}
                )
            ], style={'width': '50%', 'display': 'inline-block', 'vertical-align': 'top'}),

            html.Div([
                html.H4("Gesture Video", style={'text-align': 'center'}),
                html.Video(
                    id='gesture-video',
                    controls=True,
                    autoPlay=True,
                    loop=True,
                    style={'width': '100%'}
                )
            ], style={'width': '45%', 'display': 'inline-block', 'padding': '20px'})
        ]),

        html.Div(
            id='selected-gesture',
            style={'text-align': 'center', 'padding': '20px'}
        )
    ])

    @app.callback(
        [Output('gesture-space', 'figure'),
         Output('gesture-video', 'src'),
         Output('selected-gesture', 'children')],
        [Input('gesture-space', 'clickData')]
    )
    def update_graph(click_data):
        # Create scatter plot
        fig = px.scatter(
            df,
            x='x',
            y='y',
            hover_data=['gesture'],
            template='plotly_dark',
            labels={
                'x': 'UMAP Dimension 1',
                'y': 'UMAP Dimension 2'
            },
            title='Gesture Kinematic Space'
        )

        fig.update_traces(
            marker=dict(size=15),
            marker_color='#00CED1',
            opacity=0.7
        )

        fig.update_layout(
            hoverlabel=dict(
                bgcolor="white",
                font_size=16,
                font_family="Rockwell"
            )
        )

        # Handle video selection
        video_src = ''
        gesture_info = "Click on any point to view the gesture video"

        if click_data is not None:
            selected = click_data['points'][0]
            gesture = selected['customdata'][0]
            video_src = f'assets/{gesture}_tracked.mp4'
            gesture_info = f"Selected Gesture: {gesture}"

        return fig, video_src, gesture_info

    return app


def get_dashboard_css() -> str:
    """
    Get the CSS content for dashboard styling.

    Returns:
        CSS string with dark theme styling for the dashboard
    """
    return '''
body,
.dash-graph,
.dash-core-components,
.dash-html-components {
    margin: 0;
    background-color: #111;
    font-family: sans-serif !important;
    min-height: 100vh;
    width: 100%;
    color: #ffffff;
}

/* Modern container styling */
.dashboard-container {
    max-width: 1400px;
    margin: 0 auto;
    padding: 2rem;
    font-family: sans-serif !important;
}

/* Enhanced headings */
h1, h2, h3, h4, h5, h6 {
    color: rgba(255, 255, 255, 0.95);
    font-weight: 600;
    letter-spacing: -0.02em;
    font-family: sans-serif !important;
}

h1 {
    font-size: 2.5rem;
    text-align: center;
    margin-bottom: 2rem;
    background: linear-gradient(45deg, #fff, #a8a8a8);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    text-shadow: 0 0 30px rgba(255,255,255,0.1);
    font-family: sans-serif !important;
}

h2 {
    font-size: 1.5rem;
    margin: 1.5rem 0;
    padding-bottom: 0.5rem;
    border-bottom: 2px solid rgba(255,255,255,0.1);
    font-family: sans-serif !important;
}

/* Card-like sections */
.visualization-section {
    background: rgba(255, 255, 255, 0.03);
    border: 1px solid rgba(255, 255, 255, 0.1);
    border-radius: 12px;
    padding: 1.5rem;
    margin-bottom: 2rem;
    box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
    backdrop-filter: blur(10px);
}

/* Grid layout for kinematic features */
.kinematic-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
    gap: 1.5rem;
    margin-right: 120px;
    grid-auto-rows: minmax(200px, auto);
    height: 500px;
}

/* Video container styling */
.video-container {
    background: rgba(0, 0, 0, 0.3);
    border: 1px solid rgba(255, 255, 255, 0.1);
    border-radius: 12px;
    padding: 1rem;
    box-shadow: 0 4px 6px rgba(0, 0, 0, 0.2);
}

/* Interactive elements */
.interactive-element {
    transition: all 0.2s ease-in-out;
}

.interactive-element:hover {
    transform: translateY(-2px);
    box-shadow: 0 6px 12px rgba(0, 0, 0, 0.2);
}

/* Scrollbar styling */
::-webkit-scrollbar {
    width: 8px;
    height: 8px;
}

::-webkit-scrollbar-track {
    background: rgba(255, 255, 255, 0.1);
    border-radius: 4px;
}

::-webkit-scrollbar-thumb {
    background: rgba(255, 255, 255, 0.3);
    border-radius: 4px;
}

::-webkit-scrollbar-thumb:hover {
    background: rgba(255, 255, 255, 0.4);
}

/* Loading states */
.loading {
    opacity: 0.7;
    transition: opacity 0.3s ease;
}

/* Tooltip styling */
.tooltip {
    background: rgba(0, 0, 0, 0.8);
    border: 1px solid rgba(255, 255, 255, 0.1);
    border-radius: 6px;
    padding: 0.5rem;
    font-size: 0.875rem;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);
    font-family: sans-serif !important;
}

/* Force Dash components to use sans-serif */
.dash-plot-container,
.dash-graph-container,
.js-plotly-plot,
.plotly {
    font-family: sans-serif !important;
}
'''
