"""Create the gesture space dashboard."""

import os

import pandas as pd
import plotly.express as px
from dash import Dash, dcc, html, Input, Output

def create_dashboard(data_folder: str, assets_folder: str = "./assets"):
    """
    Create and run the gesture space visualization dashboard.
    
    Args:
        data_folder: Path to folder containing visualization data and videos
        assets_folder: Path to Dash assets folder (will store videos)
    """
    # Create assets folder if it doesn't exist
    os.makedirs(assets_folder, exist_ok=True)
    
    # Import visualization data
    df = pd.read_csv(os.path.join(data_folder, "gesture_visualization.csv"))
    
    # Adjusted: Copy tracked videos to assets from the retracked folder
    retracked_folder = os.path.join(os.path.dirname(data_folder), "retracked", "tracked_videos")
    if not os.path.exists(retracked_folder):
        raise FileNotFoundError(f"Tracked videos folder not found at {retracked_folder}")
    
    for video in os.listdir(retracked_folder):
        if video.endswith("_tracked.mp4"):
            source = os.path.join(retracked_folder, video)
            dest = os.path.join(assets_folder, video)
            if not os.path.exists(dest):
                import shutil
                shutil.copy2(source, dest)
    
    app = Dash(__name__, assets_folder=assets_folder)
    
    # App layout
    app.layout = html.Div([ 
        html.H1("ASL Gesture Kinematic Space Visualization", 
                style={'text-align': 'center'}), 
        
        html.H3("This dashboard shows a gesture kinematic space generated by computing dynamic time warping "
                "distances between ASL gesture kinematic 3D timeseries. Gestures that are closer together "
                "in the space are more kinematically similar.", 
                style={'text-align': 'center'}), 
        
        html.Div([ 
            html.Div([ 
                dcc.Graph( 
                    id='gesture-space', 
                    figure={}, 
                    style={'height': '80vh'} 
                ) 
            ], style={'width': '50%', 'display': 'inline-block', 'vertical-align': 'top'}), 
            
            html.Div([ 
                html.H4("Gesture Video", style={'text-align': 'center'}), 
                html.Video( 
                    id='gesture-video', 
                    controls=True, 
                    autoPlay=True, 
                    loop=True, 
                    style={'width': '100%'} 
                ) 
            ], style={'width': '45%', 'display': 'inline-block', 'padding': '20px'}) 
        ]), 
        
        html.Div(id='selected-gesture', 
                 style={'text-align': 'center', 'padding': '20px'}) 
    ]) 
    
    @app.callback( 
        [Output('gesture-space', 'figure'), 
         Output('gesture-video', 'src'), 
         Output('selected-gesture', 'children')], 
        [Input('gesture-space', 'clickData')] 
    ) 
    def update_graph(click_data): 
        # Create scatter plot 
        fig = px.scatter( 
            df, 
            x='x', 
            y='y', 
            hover_data=['gesture'], 
            template='plotly_dark', 
            labels={'x': 'UMAP Dimension 1', 
                   'y': 'UMAP Dimension 2'}, 
            title='Gesture Kinematic Space' 
        ) 
        
        fig.update_traces( 
            marker=dict(size=15), 
            marker_color='#00CED1', 
            opacity=0.7 
        ) 
        
        fig.update_layout( 
            hoverlabel=dict( 
                bgcolor="white", 
                font_size=16, 
                font_family="Rockwell" 
            ) 
        ) 
        
        # Handle video selection
        video_src = ''
        gesture_info = "Click on any point to view the gesture video"
        
        if click_data is not None:
            selected = click_data['points'][0]
            gesture = selected['customdata'][0]
            video_src = f'assets/{gesture}_tracked.mp4'
            gesture_info = f"Selected Gesture: {gesture}"
        
        return fig, video_src, gesture_info
    
    return app

